name: Wilderness
main: muqsit\wilderness\Wilderness
api: 4.0.0
version: 0.0.1

commands:
  wilderness:
    aliases: ["wild"]
    permission: wilderness.command

permissions:
  wilderness:
    default: false
    childrern:
      wilderness.command:
        default: op